wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713748718.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.12.2
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
num_labels:
  desc: null
  value: 4
image_size:
  desc: null
  value: 625
eps_start:
  desc: null
  value: 1.0
eps_end:
  desc: null
  value: 0.01
eps_decay:
  desc: null
  value: 5.0510204081632655e-06
max_steps:
  desc: null
  value: 200000
